---
language: ruby
ruby:
  - 2.4.2

deploy:
  provider: heroku
  api_key:
    secure: "XLip6RyFjadwxcGJERGUtig6wQzsHhiq02OW63pdQ1GrvOLxSKWq+0Pi6Gx8tBQzQSBU1Jqg0Xc5Cl8wbO/Z4fSodis9YndC5GjKBoNvHgeWwDrkFQUZ5A5SJNz8Bn9dsFrueGMZ7xiyTDX942Q6v+3u2qiE/Vt5SRh51vSNi15N/ANF4FKSCCHgQaHwgaUCW+Eue6fJgb0UFRmFu58z/V4HogjFHnqGbjIV+6m53T7Yw5Mle3aTYoPotKISIZHbe5CH9fNvJ1YELqyHAvjlqqunwNl7S/QhvRaaxokRHj27newYSw+PWfayBDTmhxaJrZnl1/EcWGaVanNIyxHqLPU+ykF601qA+vNHaQ/KbQ61uH1ntSWk03pgR7YJxcKRk/rcFTxItkAkxwv0me6xd3AM6Ol0oMrwP9BSpvuOjhb3Md5vbUoFb6TJ/TFR+TMi1xcikboePP9WAdOZMWU3rpEMZafofosrnXvPW8LfH1xOZlOis56dP81jDI54gXyTkEMjxCf7VuSnEy2ylOXjCgM1iBgyye/5VcWCiFXPm4k63aBE7EE7VqDZZi9Eo+QVwJk3+lAYqlA1onmtTCh7CO3PyWazMHAo7qugTnQcuPO80B5vNJ2tCPn4WYL6izNahFL9O67KbZVM8J7H+eBS84CT22KgdycRiBMbTbDdNj0="
